"""Add password field

Revision ID: dae5e351d58b
Revises: 4d66715c0838
Create Date: 2025-03-13 15:37:49.005272

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dae5e351d58b"
down_revision = "4d66715c0838"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###
